version: '3.5'

services:
  kotlin-rest-api:
    container_name: kotlin-rest-api
    image: kotlin-rest-api:0.0.1
    ports:
      - 8080:8080
    environment:
      DATABASE_USERNAME: kotlin
      DATABASE_PASSWORD: kotlin
      DATABASE_URL: jdbc:postgresql://kotlin-rest-api-postgres:5432/rest-api

  kotlin-rest-api-postgres:
    container_name: "kotlin-rest-api-postgres"
    image: postgres:12-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: kotlin
      POSTGRES_USER: kotlin
      POSTGRES_DB: rest-api