server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://46.250.232.65:3306/kotlin_test
    username: root
    password: secret1234

  jpa:
    hibernate:
      ddl-auto: update

logging:
  level:
    org:
      springframework: INFO
